name: Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy webhook call
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
